#spring:
#  security:
#    user:
#      name: ramesh
#      password: 123456


server:
  port: 8008
  servlet:
    context-path: /spring-security/api/

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: developer
    password: develop@mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl